apiVersion: v1
kind: Service
metadata:
  name: flask-s3-service
spec:
  selector:
    app: flask-s3
  # Đổi thành ClusterIP
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000